### ISSUE TITLE
Posts without audio should not show the audio player

### ISSUE THREAD

**Issue by cdzombak** [fatalerrorfm/jekyll-site#10]
I think this is the only affected page; note the audio player shows with the title "Error": https://fatalerror.fm/episodes/2018/5/23/episode-70-will-be-a-live-show-at-wwdc

<img width="298" alt="Screen Shot 2020-04-02 at 1 16 02 PM" src="https://user-images.githubusercontent.com/102904/78278485-1b715880-74e4-11ea-8815-150895bebbc1.png">

**Comment by khanlou** [comment]
Fixed and pushed up in 7a7bd7aa0e1552c3ca37c9a873a8abab3d5de7e2. Deploy whenever

**Comment by cdzombak** [comment]
Thanks, @khanlou. Hope all is well 🍻
