### ISSUE TITLE
Transfer domain & DNS

### ISSUE THREAD

**Issue by cdzombak** [fatalerrorfm/jekyll-site#4]
- [x] **Chris:** set up DNS records at DigitalOcean for fatalerror.fm matching those that Squarespace uses
- [x] transfer the domain to a registrar where one of us has an account
- [x] point the NS records to `ns[1-3].digitalocean.com`

In the future, when we are ready to deploy for real, Chris can just update the DNS records at DigitalOcean to point to his webserver instead of Squarespace.

Ref:
- [Connecting a domain to your Squarespace site – Squarespace Help](https://support.squarespace.com/hc/en-us/articles/205812378-Connecting-a-domain-to-your-Squarespace-site)

**Comment by cdzombak** [comment]
DNS from Sqsp:

```
cdzombak@fresnel  ~/code/fatalerror-jekyll   master  dig fatalerror.fm

; <<>> DiG 9.10.6 <<>> fatalerror.fm
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56036
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;fatalerror.fm.			IN	A

;; ANSWER SECTION:
fatalerror.fm.		3600	IN	A	198.49.23.144
fatalerror.fm.		3600	IN	A	198.49.23.145
fatalerror.fm.		3600	IN	A	198.185.159.144
fatalerror.fm.		3600	IN	A	198.185.159.145

;; Query time: 47 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111)
;; WHEN: Wed Feb 19 14:39:22 EST 2020
;; MSG SIZE  rcvd: 106

 cdzombak@fresnel  ~/code/fatalerror-jekyll   master  dig www.fatalerror.fm

; <<>> DiG 9.10.6 <<>> www.fatalerror.fm
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3457
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;www.fatalerror.fm.		IN	A

;; ANSWER SECTION:
www.fatalerror.fm.	3600	IN	CNAME	ext-cust.squarespace.com.
ext-cust.squarespace.com. 9787	IN	A	198.49.23.145
ext-cust.squarespace.com. 9787	IN	A	198.185.159.144
ext-cust.squarespace.com. 9787	IN	A	198.185.159.145
ext-cust.squarespace.com. 9787	IN	A	198.49.23.144

;; Query time: 41 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111)
;; WHEN: Wed Feb 19 14:39:52 EST 2020
;; MSG SIZE  rcvd: 148
```

**Comment by cdzombak** [comment]
Assigning to me since first action is mine; then @khanlou can take over

**Comment by khanlou** [comment]
Feel free to tag me on this when it's time, I can move it to my iwantmyname account

**Comment by cdzombak** [comment]
@khanlou okay, I believe I've cloned the requisite DNS config to my DigitalOcean account. we should be able to move forward with transferring the domain & setting nameservers to `ns1.digitalocean.com, ns2.digitalocean.com, ns3.digitalocean.com`.
