### ISSUE TITLE
Update feed URL in document <head>

### ISSUE THREAD

**Issue by cdzombak** [fatalerrorfm/jekyll-site#6]
Currently, all our pages point to `/feed.xml` in the `<head>`:

```
<link rel="alternate" type="application/rss+xml" title="Fatal Error" href="/feed.xml">
```

They should point to `/rss.xml` instead.

**Comment by khanlou** [comment]
I think for this we need to "clone" the Minima template into our repo and then edit it manually. Not sure if there's any other way to get this done
