### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by cdzombak** [fatalerrorfm/jekyll-site#9]
Waiting on a final 👍 from @khanlou, then I will:

- [x] point fatalerror.fm DNS at my server
- [x] get a cert issued through Lets Encrypt
- [x] enable the site in nginx

and we'll be good to go.

**Comment by khanlou** [comment]
Ready from my perspective!

**Comment by cdzombak** [comment]
`[www.]fatalerror.fm` is being served live from my server now. 🍻

**Comment by cdzombak** [comment]
Pocket Casts isn't showing any "new" episodes and I downloaded a couple and saw them coming from my server. Success 🎉

**Comment by khanlou** [comment]
Amazing! Great work everyone!
